### ISSUE TITLE
Crash on update

### ISSUE THREAD

**Issue by CyborgForever** [dokkaner/dokkaner#10]
Took a look at the other issues, mine seems to be different ?
Maybe similar to #7 , but the log is really different so...
[trace.log](https://github.com/dokkaner/dokkaner/files/1799326/trace.log)
No folder "dokkaner" in C:\ProgramData

I can download the update, and on the restart, it simply crash, and the data is not updated

**Comment by kassatsu** [comment]
I am seeing the same issues as above. 

No folder created in C:\Program Data and it will crash when attempting to restart after downloading asset update.

[trace.log](https://github.com/dokkaner/dokkaner/files/1800073/trace.log)
