### ISSUE TITLE
Exclude Card Bug

### ISSUE THREAD

**Issue by unmonk** [dokkaner/dokkaner#2]
Howdy,

Ran into a reproducible issue with excluding a card from a team.

Info: 
SSJ4 Gogeta 
Stick to Leader Type:  **True**
**Balanced**
Range: **SR - LR**
Only My Cards: **False**
Show Rotations: **False**

Any card I select and choose Exclude will cause all cards except the leader to be removed from the team. Does not generate a new one. 

![dokkan](https://user-images.githubusercontent.com/8887802/37182416-106f98e0-22e6-11e8-9415-281f6d228bb1.PNG)

**Comment by dokkaner** [comment]
Thanks for reporting. I can also reproduce it. I think that goes for all the category leaders. There must be a conflict over the leader's giving to a category and type. I'm going to investigate.
