### ISSUE TITLE
Affinity Inconsistencies

### ISSUE THREAD

**Issue by Satorha** [dokkaner/dokkaner#3]
Hello.

I jumped in to test things instantly after I saw the post (I wanted to see how useful the tool is overall compared to things like simple google searches) and I found an inconsistency that I'll start to look for more of. 

LR Vegito Blue and PHY Super Vegito, in the affinities tab, do not seem to share any links. However, on LR Vegito Blue's side, AGL Super Vegito shows just fine while on PHY Super Vegito's side, PHY Vegito Blue shows just fine.

I'm honestly not sure if this is a bug. It seems to happen with cards where there are more than two of the same name (for example, INT Super Gogeta does not show up in any of these affinity tabs either when viewing from either of the four cards I mentioned while STR Super Gogeta shows just fine).

**Comment by dokkaner** [comment]
I think it's a bug, actually because of the names of the Cards. Well, I guess. I'll take a look.
