### ISSUE TITLE
[Solved]Can't update the app

### ISSUE THREAD

**Issue by Hanasagi** [dokkaner/dokkaner#5]
I have this error when I try to update the app
![](https://puu.sh/zDR43/795bb4f958.png)

**Comment by dokkaner** [comment]
Hi, can you attach your trace.log file please?  C:\Users\ `youruser ` \AppData\Local\dokkaner\logs\

**Comment by Xeltorr** [comment]
Hi; I have the exact same problem, I can't use the app at all; here is my file 
Hope you can fix it; your app looks awesome
[trace.log](https://github.com/dokkaner/dokkaner/files/1796734/trace.log)

**Comment by dokkaner** [comment]
Hi! Try to give rights to all users on the C:\ProgramData\dokkaner\data directory. ie: in C:\ProgramData\dokkaner\ do a right clic on the Data directory and chose "properties" and then the "security" tab. and Give all the permissions to the users group.
Tell me if it working

**Comment by Xeltorr** [comment]
Hi; thanks for the response; well something did change, but I still get this error when launching the app:
http://image.noelshack.com/fichiers/2018/10/5/1520596944-error-8.png
they say there is a problem with the database:
http://image.noelshack.com/fichiers/2018/10/5/1520596944-error9.png
and I still have the same problem:
http://image.noelshack.com/fichiers/2018/10/5/1520596944-dededeedededede.png

**Comment by dokkaner** [comment]
![perm_rights](https://user-images.githubusercontent.com/28895460/37207473-8056a308-239d-11e8-8392-950fcfcb3bf0.PNG)
Can u show me your security settings for this directory? it must be like this

**Comment by Hanasagi** [comment]
here's mine
[trace.log](https://github.com/dokkaner/dokkaner/files/1796888/trace.log)

**Comment by dokkaner** [comment]
@Hanasagi do you use a proxy? The app cant reach somes web api

**Comment by Hanasagi** [comment]
nope :/

**Comment by Xeltorr** [comment]
So; it does work now; I did what you said; thanks! I thought you were talking about another dokkaner folder (si tu es français comme le suggère ta page, j'ai qu'une chose a dire: Bien joué!)

**Comment by dokkaner** [comment]
Cool, Merci ! :)

**Comment by Vulcode** [comment]
S'il vous plait je ne peux pas modifier la sécurité du dosssier, j'ai du coup les même probleme que Xeltorr.

**Comment by Hanasagi** [comment]
Et donc ? qu'est-ce qui pourrais bloquer le fais de pas trouver l'api ? J'ai pas de proxy pourtant /:

**Comment by MiguiTR** [comment]
I have installed the app but I can't find the "ProgramData/dokkaner" directory https://i.gyazo.com/18e5daab8a5968ce0dc76d1e0bdfcd44.png
