### ISSUE TITLE
Error [8]

### ISSUE THREAD

**Issue by DepecheMV** [dokkaner/dokkaner#6]
I got this error on windows 10, when I try to open this.
It stucks at 21% of data download and then bum! this.

https://imgur.com/a/vH7iQ

When this works, I would make a video on my Youtube Spanish channel to let your software more known... I think its very very useful!

**Comment by dokkaner** [comment]
Can you show me the security settings for this directory C:\ProgramData\dokkaner\data ?
The permissions must be set like this:

![perm_rights](https://user-images.githubusercontent.com/28895460/37207758-afe55f64-239e-11e8-8ec6-4f6c39c921c1.PNG)
With great pleasure to share the app!
