### ISSUE TITLE
can't see anything

### ISSUE THREAD

**Issue by Gunrell** [dokkaner/dokkaner#7]
whenever i open the app i get this screen but nothing is inside
![image](https://user-images.githubusercontent.com/21602005/37210429-f9c4613e-23a8-11e8-8c48-e6aedca139ba.png)

Any idea ?

Edit:

here's what is in the log:

`2018/03/09 15:00:31.276 - 96 [9492] trace Dokkaner  - Initializing app:Dokkaner`
`2018/03/09 15:00:31.279 - 99 [9492] trace Dokkaner  - app version:0.91.6641.14238`
`2018/03/09 15:00:33.108 - 1928 [3932] trace Dokkaner  - amplitude StartSession monitor result: success`
`2018/03/09 15:00:33.109 - 1929 [9492] trace Dokkaner  - amplitude RecordEvent monitor result: success`
`2018/03/09 15:00:33.235 - 2055 [9492] trace Dokkaner  - Repo init`
`2018/03/09 15:00:33.236 - 2056 [9492] trace Dokkaner  - Load database`
`2018/03/09 15:00:36.569 - 5389 [9492] trace Dokkaner  - try read Influence`
`2018/03/09 15:00:38.209 - 7029 [9492] trace Dokkaner  - Loading UserCardBox`
`2018/03/09 15:00:38.209 - 7029 [9492] trace Dokkaner  - No box found; creating one`
`2018/03/09 15:00:38.211 - 7031 [9492] trace Dokkaner  - Saving UserCardBox `
`2018/03/09 15:00:39.802 - 8622 [9492] warn Dokkaner  - getCardById error: Invalid parameter`
`2018/03/09 15:00:41.152 - 9972 [9492] warn Dokkaner  - getCardById error: Card not found. Name:Super Saiyan Gohan (Teen) - Brother's Will`
`2018/03/09 15:00:41.167 - 9987 [9492] warn Dokkaner  - getCardById error: Card not found. Name:Super Saiyan Goku - Father's Pride`
`2018/03/09 15:00:41.169 - 9989 [9492] warn Dokkaner  - getCardById error: Card not found. Name:Super Saiyan Goten (Kid) - Brother's Wish`
`2018/03/09 15:00:41.181 - 10001 [9492] warn Dokkaner  - getCardById error: Invalid parameter`
`2018/03/09 15:00:42.415 - 11235 [9492] warn Dokkaner  - getCardById error: Card not found. Name:Super Saiyan Gohan (Teen) - Brother's Will`
`2018/03/09 15:00:42.428 - 11248 [9492] warn Dokkaner  - getCardById error: Card not found. Name:Super Saiyan Goten (Kid) - Brother's Wish`
`2018/03/09 15:00:42.458 - 11278 [9492] warn Dokkaner  - getCardById error: Card not found. Name:Super Saiyan Goku - Father's Pride`
`2018/03/09 15:00:42.488 - 11308 [9492] warn Dokkaner  - getCardById error: Invalid parameter`
`2018/03/09 15:00:43.269 - 12089 [9492] warn Dokkaner  - getCardById error: Card not found. Name:Hercule Statue (Diamond) - Worth 5,000,000 Zeni`
`2018/03/09 15:00:43.270 - 12090 [9492] warn Dokkaner  - getCardById error: Card not found. Name:Hercule Statue (Platinum) - 1.5 Million-Zeni Price Tag`
`2018/03/09 15:00:43.270 - 12090 [9492] warn Dokkaner  - getCardById error: Card not found. Name:Hercule Statue (Gold) - Worth 1 Million Zeni`
`2018/03/09 15:00:43.270 - 12090 [9492] warn Dokkaner  - getCardById error: Invalid parameter`
`2018/03/09 15:00:44.897 - 13717 [9492] warn Dokkaner  - getCardById error: Card not found. Name:Hercule Statue (Gold) - Worth 1 Million Zeni`
`2018/03/09 15:00:44.900 - 13720 [9492] warn Dokkaner  - getCardById error: Card not found. Name:Hercule - Earth's Savior`
`2018/03/09 15:00:44.904 - 13724 [9492] warn Dokkaner  - getCardById error: Card not found. 
Name:Hercule Statue (Silver) - Worth 500,000 Zeni`
`2018/03/09 15:00:44.917 - 13737 [9492] warn Dokkaner  - getCardById error: Card not found. Name:Hercule Statue (Bronze) - Worth 250,000 Zeni`
`2018/03/09 15:00:44.943 - 13763 [9492] warn Dokkaner  - getCardById error: Invalid parameter`
`2018/03/09 15:00:46.329 - 15149 [9492] trace Dokkaner  - [USER] Open Cards view`
`2018/03/09 15:00:46.329 - 15149 [9492] trace Dokkaner  - filteredGetCards`
`2018/03/09 15:00:47.538 - 16358 [9492] trace Dokkaner  - Repo GetEvents`
`2018/03/09 15:00:51.276 - 20096 [9492] trace Dokkaner  - onesignal View Pushs result: total_count 0`

**Comment by dokkaner** [comment]
Hi, have you theses items in C:\ProgramData\dokkaner\data\ ?
-- dokkan.global file
-- Assets dir
